services:
  web:
    build: ./nginx
    ports:
      - 8080:80
    develop:
      watch:
        - action: sync
          path: ./nginx/public/
          target: /usr/share/nginx/html/
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
    depends_on:
      - adminer
      - api

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  # UI tool for postgres, pretty cool
  adminer:
    image: adminer
    depends_on:
      - db

  api:
    build: ./be
    env_file:
      - ./be/.env
    develop:
      watch:
        - action: sync+restart
          path: ./be
          target: /app
    depends_on:
      - db

  data-harvester:
    build: ./data-harvester
    develop:
      watch:
        - action: rebuild
          path: ./data-harvester
          target: /app
    depends_on:
      - db

volumes:
  pgdata:
